FROM python:3.10-slim
WORKDIR /tgdlf
COPY . .
RUN pip config set global.index-url http://mirrors.aliyun.com/pypi/simple \
    && pip config set install.trusted-host mirrors.aliyun.com \
    && pip install --disable-pip-version-check -r requirements.txt \
    && cd /tgdlf/enn && python setup.py install \
    && cd /tgdlf && python setup.py install
CMD /bin/bash
