FROM python:3.10-slim
WORKDIR /tgdlf
COPY enn /tgdlf
COPY grid_configuration.py /tgdlf
COPY grid_data_v2.py /tgdlf
COPY grid_LSTM.py /tgdlf
COPY train_decay_loss.py /tgdlf
COPY util.py /tgdlf
COPY requirements.txt /tgdlf
RUN pip install -r requirements.txt
CMD /bin/bash
